### ISSUE TITLE
Document nprogress installation

### ISSUE THREAD

**Issue by pelletiermaxime** [imcvampire/vue-resource-nprogress#1]
Hi, thank you for the great plugin.
Can I suggest better documentation on how to install nprogress ? Here is what I used (in webpack):

``` javascript
npm i nprogress
import NProgress from 'nprogress'
window.NProgress = NProgress
require('nprogress/nprogress.css')
```

**Comment by imcvampire** [comment]
Thanks for your better documentation! I will update it when I have my laptop back (I'm using mobile now).
